---
functional:
  - Пользователь должен иметь возможность авторизоваться на сайте 
  - Пользователь должен иметь возможность создать задачу и ждать соперника
  - Пользователь должен иметь возможность вступать в открытые игры
  - Пользователи должны иметь возможность зайти запущенную игру можно зайти в качестве зрителя
  - Пользователь должен иметь возможность решить задачу на удобном языке прокграммирования
  - Пользователь должен иметь возможность видеть в реальном времени код соперника и результаты запуска тестов
  - Пользователь должен иметь возможность общаться с соперником и зрителями в чате
  - Победа должна присуждаться игроку, который первый решил задачу
  - Каждый игрок имеет кнопку "Run" для проверки своего решения. Попыток проверки неограниченно
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть
  - Вылетевший игрок в любой момент игры, пока она не закончена, может переподключиться в игру
  - Игра пока может длиться неограниченное время
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
  - Пользователь должен иметь возможность выбрать сложность для созданной игры
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Должно быть расширение для браузера Chrom, чтобы была возможность следить за открытыми играми без посещения сайта
  - Сайт должен корректно отображаться в любых браузерах
  - На сайте должны быть возможность подписаться на премиум
implicit:
  - Пользователь не может отправять пустые сообщения в чат
  - Пользователь не может отправлять бесконечно длинные сообщения в чат
  - Должна быть возможнось авторизоваться с помощью GitHup
  - Ник пользователя на сайте должен быть уникальным
  - требование 6
